language: python

python:
  - "2.7"

cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - libxml2-dev
      - libxmlsec1-dev
      - libxslt-dev

env:
  - VERSION="10.0" LINT_CHECK="1"
  - VERSION="10.0" ODOO_REPO="multidadosti-erp/odoo" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/multidadosti-erp/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install -r requirements.txt

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
