language: python

python:
  - "2.7"

cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - libxml2-dev
      - libxmlsec1-dev
      - libxslt-dev

env:
  - VERSION="10.0" LINT_CHECK="1"
  - VERSION="10.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codacy-coverage
  - travis_install_nightly

script:
  - ./configure_locale.sh
  - cd ${HOME}/maintainer-quality-tools
  - coverage run --append ./travis/travis_run_tests 10.0  # only used if VERSION not set in env
  - coverage xml

after_success:
  - python-codacy-coverage -c $TRAVIS_COMMIT -r coverage.xml
